// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorboard/compat/proto/summary.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _3: SwiftProtobuf.ProtobufAPIVersion_3 {}
  typealias Version = _3
}

enum Tensorboard_DataClass: SwiftProtobuf.Enum {
  typealias RawValue = Int

  /// Unknown data class, used (implicitly) for legacy data. Will not be
  /// processed by data ingestion pipelines.
  case unknown // = 0

  /// Scalar time series. Each `Value` for the corresponding tag must have
  /// `tensor` set to a rank-0 tensor of type `DT_FLOAT` (float32).
  case scalar // = 1

  /// Tensor time series. Each `Value` for the corresponding tag must have
  /// `tensor` set. The tensor value is arbitrary, but should be small to
  /// accommodate direct storage in database backends: an upper bound of a few
  /// kilobytes is a reasonable rule of thumb.
  case tensor // = 2

  /// Blob sequence time series. Each `Value` for the corresponding tag must
  /// have `tensor` set to a rank-1 tensor of bytestring dtype.
  case blobSequence // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .scalar
    case 2: self = .tensor
    case 3: self = .blobSequence
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .scalar: return 1
    case .tensor: return 2
    case .blobSequence: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Tensorboard_DataClass] = [
    .unknown,
    .scalar,
    .tensor,
    .blobSequence,
  ]

}

/// Metadata associated with a series of Summary data
struct Tensorboard_SummaryDescription {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Hint on how plugins should process the data in this series.
  /// Supported values include "scalar", "histogram", "image", "audio"
  var typeHint: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Serialization format for histogram module in
/// core/lib/histogram/histogram.h
struct Tensorboard_HistogramProto {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var min: Double = 0

  var max: Double = 0

  var num: Double = 0

  var sum: Double = 0

  var sumSquares: Double = 0

  /// Parallel arrays encoding the bucket boundaries and the bucket values.
  /// bucket(i) is the count for the bucket i.  The range for
  /// a bucket is:
  ///   i == 0:  -DBL_MAX .. bucket_limit(0)
  ///   i != 0:  bucket_limit(i-1) .. bucket_limit(i)
  var bucketLimit: [Double] = []

  var bucket: [Double] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A SummaryMetadata encapsulates information on which plugins are able to make
/// use of a certain summary value.
struct Tensorboard_SummaryMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Data that associates a summary with a certain plugin.
  var pluginData: Tensorboard_SummaryMetadata.PluginData {
    get {return _pluginData ?? Tensorboard_SummaryMetadata.PluginData()}
    set {_pluginData = newValue}
  }
  /// Returns true if `pluginData` has been explicitly set.
  var hasPluginData: Bool {return self._pluginData != nil}
  /// Clears the value of `pluginData`. Subsequent reads from it will return its default value.
  mutating func clearPluginData() {self._pluginData = nil}

  /// Display name for viewing in TensorBoard.
  var displayName: String = String()

  /// Longform readable description of the summary sequence. Markdown supported.
  var summaryDescription: String = String()

  /// Class of data stored in this time series. Required for compatibility with
  /// TensorBoard's generic data facilities (`DataProvider`, et al.). This value
  /// imposes constraints on the dtype and shape of the corresponding tensor
  /// values. See `DataClass` docs for details.
  var dataClass: Tensorboard_DataClass = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct PluginData {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The name of the plugin this data pertains to.
    var pluginName: String = String()

    /// The content to store for the plugin. The best practice is for this to be
    /// a binary serialized protocol buffer.
    var content: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _pluginData: Tensorboard_SummaryMetadata.PluginData? = nil
}

/// A Summary is a set of named values to be displayed by the
/// visualizer.
///
/// Summaries are produced regularly during training, as controlled by
/// the "summary_interval_secs" attribute of the training operation.
/// Summaries are also produced at the end of an evaluation.
struct Tensorboard_Summary {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Set of values for the summary.
  var value: [Tensorboard_Summary.Value] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Image {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Dimensions of the image.
    var height: Int32 = 0

    var width: Int32 = 0

    /// Valid colorspace values are
    ///   1 - grayscale
    ///   2 - grayscale + alpha
    ///   3 - RGB
    ///   4 - RGBA
    ///   5 - DIGITAL_YUV
    ///   6 - BGRA
    var colorspace: Int32 = 0

    /// Image data in encoded format.  All image formats supported by
    /// image_codec::CoderUtil can be stored here.
    var encodedImageString: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Audio {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Sample rate of the audio in Hz.
    var sampleRate: Float = 0

    /// Number of channels of audio.
    var numChannels: Int64 = 0

    /// Length of the audio in frames (samples per channel).
    var lengthFrames: Int64 = 0

    /// Encoded audio data and its associated RFC 2045 content type (e.g.
    /// "audio/wav").
    var encodedAudioString: Data = Data()

    var contentType: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Value {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// This field is deprecated and will not be set.
    var nodeName: String = String()

    /// Tag name for the data. Used by TensorBoard plugins to organize data. Tags
    /// are often organized by scope (which contains slashes to convey
    /// hierarchy). For example: foo/bar/0
    var tag: String = String()

    /// Contains metadata on the summary value such as which plugins may use it.
    /// Take note that many summary values may lack a metadata field. This is
    /// because the FileWriter only keeps a metadata object on the first summary
    /// value with a certain tag for each tag. TensorBoard then remembers which
    /// tags are associated with which plugins. This saves space.
    var metadata: Tensorboard_SummaryMetadata {
      get {return _metadata ?? Tensorboard_SummaryMetadata()}
      set {_metadata = newValue}
    }
    /// Returns true if `metadata` has been explicitly set.
    var hasMetadata: Bool {return self._metadata != nil}
    /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
    mutating func clearMetadata() {self._metadata = nil}

    /// Value associated with the tag.
    var value: Tensorboard_Summary.Value.OneOf_Value? = nil

    var simpleValue: Float {
      get {
        if case .simpleValue(let v)? = value {return v}
        return 0
      }
      set {value = .simpleValue(newValue)}
    }

    var obsoleteOldStyleHistogram: Data {
      get {
        if case .obsoleteOldStyleHistogram(let v)? = value {return v}
        return Data()
      }
      set {value = .obsoleteOldStyleHistogram(newValue)}
    }

    var image: Tensorboard_Summary.Image {
      get {
        if case .image(let v)? = value {return v}
        return Tensorboard_Summary.Image()
      }
      set {value = .image(newValue)}
    }

    var histo: Tensorboard_HistogramProto {
      get {
        if case .histo(let v)? = value {return v}
        return Tensorboard_HistogramProto()
      }
      set {value = .histo(newValue)}
    }

    var audio: Tensorboard_Summary.Audio {
      get {
        if case .audio(let v)? = value {return v}
        return Tensorboard_Summary.Audio()
      }
      set {value = .audio(newValue)}
    }

    var tensor: Tensorboard_TensorProto {
      get {
        if case .tensor(let v)? = value {return v}
        return Tensorboard_TensorProto()
      }
      set {value = .tensor(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    /// Value associated with the tag.
    enum OneOf_Value: Equatable {
      case simpleValue(Float)
      case obsoleteOldStyleHistogram(Data)
      case image(Tensorboard_Summary.Image)
      case histo(Tensorboard_HistogramProto)
      case audio(Tensorboard_Summary.Audio)
      case tensor(Tensorboard_TensorProto)

    }

    init() {}

    fileprivate var _metadata: Tensorboard_SummaryMetadata? = nil
  }

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Tensorboard_SummaryDescription: @unchecked Sendable {}
extension Tensorboard_HistogramProto: @unchecked Sendable {}
extension Tensorboard_SummaryMetadata: @unchecked Sendable {}
extension Tensorboard_SummaryMetadata.PluginData: @unchecked Sendable {}
extension Tensorboard_Summary: @unchecked Sendable {}
extension Tensorboard_Summary.Image: @unchecked Sendable {}
extension Tensorboard_Summary.Audio: @unchecked Sendable {}
extension Tensorboard_Summary.Value: @unchecked Sendable {}
extension Tensorboard_Summary.Value.OneOf_Value: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorboard"

extension Tensorboard_DataClass: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DATA_CLASS_UNKNOWN"),
    1: .same(proto: "DATA_CLASS_SCALAR"),
    2: .same(proto: "DATA_CLASS_TENSOR"),
    3: .same(proto: "DATA_CLASS_BLOB_SEQUENCE"),
  ]
}

extension Tensorboard_SummaryDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SummaryDescription"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "type_hint"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeHint) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.typeHint.isEmpty {
      try visitor.visitSingularStringField(value: self.typeHint, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_SummaryDescription, rhs: Tensorboard_SummaryDescription) -> Bool {
    if lhs.typeHint != rhs.typeHint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_HistogramProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HistogramProto"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "min"),
    2: .same(proto: "max"),
    3: .same(proto: "num"),
    4: .same(proto: "sum"),
    5: .standard(proto: "sum_squares"),
    6: .standard(proto: "bucket_limit"),
    7: .same(proto: "bucket"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.min) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.max) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.num) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.sum) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.sumSquares) }()
      case 6: try { try decoder.decodeRepeatedDoubleField(value: &self.bucketLimit) }()
      case 7: try { try decoder.decodeRepeatedDoubleField(value: &self.bucket) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.min != 0 {
      try visitor.visitSingularDoubleField(value: self.min, fieldNumber: 1)
    }
    if self.max != 0 {
      try visitor.visitSingularDoubleField(value: self.max, fieldNumber: 2)
    }
    if self.num != 0 {
      try visitor.visitSingularDoubleField(value: self.num, fieldNumber: 3)
    }
    if self.sum != 0 {
      try visitor.visitSingularDoubleField(value: self.sum, fieldNumber: 4)
    }
    if self.sumSquares != 0 {
      try visitor.visitSingularDoubleField(value: self.sumSquares, fieldNumber: 5)
    }
    if !self.bucketLimit.isEmpty {
      try visitor.visitPackedDoubleField(value: self.bucketLimit, fieldNumber: 6)
    }
    if !self.bucket.isEmpty {
      try visitor.visitPackedDoubleField(value: self.bucket, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_HistogramProto, rhs: Tensorboard_HistogramProto) -> Bool {
    if lhs.min != rhs.min {return false}
    if lhs.max != rhs.max {return false}
    if lhs.num != rhs.num {return false}
    if lhs.sum != rhs.sum {return false}
    if lhs.sumSquares != rhs.sumSquares {return false}
    if lhs.bucketLimit != rhs.bucketLimit {return false}
    if lhs.bucket != rhs.bucket {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_SummaryMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SummaryMetadata"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "plugin_data"),
    2: .standard(proto: "display_name"),
    3: .standard(proto: "summary_description"),
    4: .standard(proto: "data_class"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._pluginData) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.summaryDescription) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.dataClass) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._pluginData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if !self.summaryDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.summaryDescription, fieldNumber: 3)
    }
    if self.dataClass != .unknown {
      try visitor.visitSingularEnumField(value: self.dataClass, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_SummaryMetadata, rhs: Tensorboard_SummaryMetadata) -> Bool {
    if lhs._pluginData != rhs._pluginData {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.summaryDescription != rhs.summaryDescription {return false}
    if lhs.dataClass != rhs.dataClass {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_SummaryMetadata.PluginData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_SummaryMetadata.protoMessageName + ".PluginData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "plugin_name"),
    2: .same(proto: "content"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pluginName) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pluginName.isEmpty {
      try visitor.visitSingularStringField(value: self.pluginName, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_SummaryMetadata.PluginData, rhs: Tensorboard_SummaryMetadata.PluginData) -> Bool {
    if lhs.pluginName != rhs.pluginName {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_Summary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Summary"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_Summary, rhs: Tensorboard_Summary) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_Summary.Image: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_Summary.protoMessageName + ".Image"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "height"),
    2: .same(proto: "width"),
    3: .same(proto: "colorspace"),
    4: .standard(proto: "encoded_image_string"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.colorspace) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.encodedImageString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 1)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 2)
    }
    if self.colorspace != 0 {
      try visitor.visitSingularInt32Field(value: self.colorspace, fieldNumber: 3)
    }
    if !self.encodedImageString.isEmpty {
      try visitor.visitSingularBytesField(value: self.encodedImageString, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_Summary.Image, rhs: Tensorboard_Summary.Image) -> Bool {
    if lhs.height != rhs.height {return false}
    if lhs.width != rhs.width {return false}
    if lhs.colorspace != rhs.colorspace {return false}
    if lhs.encodedImageString != rhs.encodedImageString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_Summary.Audio: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_Summary.protoMessageName + ".Audio"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "sample_rate"),
    2: .standard(proto: "num_channels"),
    3: .standard(proto: "length_frames"),
    4: .standard(proto: "encoded_audio_string"),
    5: .standard(proto: "content_type"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.sampleRate) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.numChannels) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.lengthFrames) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.encodedAudioString) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sampleRate != 0 {
      try visitor.visitSingularFloatField(value: self.sampleRate, fieldNumber: 1)
    }
    if self.numChannels != 0 {
      try visitor.visitSingularInt64Field(value: self.numChannels, fieldNumber: 2)
    }
    if self.lengthFrames != 0 {
      try visitor.visitSingularInt64Field(value: self.lengthFrames, fieldNumber: 3)
    }
    if !self.encodedAudioString.isEmpty {
      try visitor.visitSingularBytesField(value: self.encodedAudioString, fieldNumber: 4)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_Summary.Audio, rhs: Tensorboard_Summary.Audio) -> Bool {
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.numChannels != rhs.numChannels {return false}
    if lhs.lengthFrames != rhs.lengthFrames {return false}
    if lhs.encodedAudioString != rhs.encodedAudioString {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_Summary.Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_Summary.protoMessageName + ".Value"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    7: .standard(proto: "node_name"),
    1: .same(proto: "tag"),
    9: .same(proto: "metadata"),
    2: .standard(proto: "simple_value"),
    3: .standard(proto: "obsolete_old_style_histogram"),
    4: .same(proto: "image"),
    5: .same(proto: "histo"),
    6: .same(proto: "audio"),
    8: .same(proto: "tensor"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 2: try {
        var v: Float?
        try decoder.decodeSingularFloatField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .simpleValue(v)
        }
      }()
      case 3: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .obsoleteOldStyleHistogram(v)
        }
      }()
      case 4: try {
        var v: Tensorboard_Summary.Image?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .image(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .image(v)
        }
      }()
      case 5: try {
        var v: Tensorboard_HistogramProto?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .histo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .histo(v)
        }
      }()
      case 6: try {
        var v: Tensorboard_Summary.Audio?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .audio(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .audio(v)
        }
      }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.nodeName) }()
      case 8: try {
        var v: Tensorboard_TensorProto?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .tensor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .tensor(v)
        }
      }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 1)
    }
    switch self.value {
    case .simpleValue?: try {
      guard case .simpleValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    }()
    case .obsoleteOldStyleHistogram?: try {
      guard case .obsoleteOldStyleHistogram(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    }()
    case .image?: try {
      guard case .image(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .histo?: try {
      guard case .histo(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .audio?: try {
      guard case .audio(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    default: break
    }
    if !self.nodeName.isEmpty {
      try visitor.visitSingularStringField(value: self.nodeName, fieldNumber: 7)
    }
    try { if case .tensor(let v)? = self.value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_Summary.Value, rhs: Tensorboard_Summary.Value) -> Bool {
    if lhs.nodeName != rhs.nodeName {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
