// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorboard/compat/proto/trackable_object_graph.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _3: SwiftProtobuf.ProtobufAPIVersion_3 {}
  typealias Version = _3
}

struct Tensorboard_TrackableObjectGraph {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nodes: [Tensorboard_TrackableObjectGraph.TrackableObject] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct TrackableObject {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Objects which this object depends on.
    var children: [Tensorboard_TrackableObjectGraph.TrackableObject.ObjectReference] = []

    /// Serialized data specific to this object.
    var attributes: [Tensorboard_TrackableObjectGraph.TrackableObject.SerializedTensor] = []

    /// Slot variables owned by this object.
    var slotVariables: [Tensorboard_TrackableObjectGraph.TrackableObject.SlotVariableReference] = []

    /// The registered saver used to save this object. If this saver is not
    /// present when loading the checkpoint, then loading will fail.
    var registeredSaver: Tensorboard_RegisteredSaver {
      get {return _registeredSaver ?? Tensorboard_RegisteredSaver()}
      set {_registeredSaver = newValue}
    }
    /// Returns true if `registeredSaver` has been explicitly set.
    var hasRegisteredSaver: Bool {return self._registeredSaver != nil}
    /// Clears the value of `registeredSaver`. Subsequent reads from it will return its default value.
    mutating func clearRegisteredSaver() {self._registeredSaver = nil}

    /// Whether this object has checkpoint values or descendants with checkpoint
    /// values. This is computed at save time to avoid traversing the entire
    /// object graph proto when restoring (which also has to traverse the live
    /// object graph).
    var hasCheckpointValues_p: SwiftProtobuf.Google_Protobuf_BoolValue {
      get {return _hasCheckpointValues_p ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
      set {_hasCheckpointValues_p = newValue}
    }
    /// Returns true if `hasCheckpointValues_p` has been explicitly set.
    var hasHasCheckpointValues_p: Bool {return self._hasCheckpointValues_p != nil}
    /// Clears the value of `hasCheckpointValues_p`. Subsequent reads from it will return its default value.
    mutating func clearHasCheckpointValues_p() {self._hasCheckpointValues_p = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct ObjectReference {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// An index into `TrackableObjectGraph.nodes`, indicating the object
      /// being referenced.
      var nodeID: Int32 = 0

      /// A user-provided name for the edge.
      var localName: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct SerializedTensor {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// A name for the Tensor. Simple variables have only one
      /// `SerializedTensor` named "VARIABLE_VALUE" by convention. This value may
      /// be restored on object creation as an optimization.
      var name: String = String()

      /// The full name of the variable/tensor, if applicable. Used to allow
      /// name-based loading of checkpoints which were saved using an
      /// object-based API. Should match the checkpoint key which would have been
      /// assigned by tf.train.Saver.
      var fullName: String = String()

      /// The generated name of the Tensor in the checkpoint.
      var checkpointKey: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct SlotVariableReference {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// An index into `TrackableObjectGraph.nodes`, indicating the
      /// variable object this slot was created for.
      var originalVariableNodeID: Int32 = 0

      /// The name of the slot (e.g. "m"/"v").
      var slotName: String = String()

      /// An index into `TrackableObjectGraph.nodes`, indicating the
      /// `Object` with the value of the slot variable.
      var slotVariableNodeID: Int32 = 0

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}

    fileprivate var _registeredSaver: Tensorboard_RegisteredSaver? = nil
    fileprivate var _hasCheckpointValues_p: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
  }

  init() {}
}

struct Tensorboard_RegisteredSaver {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the registered saver/restore function.
  var name: String = String()

  /// Unique auto-generated name of the object.
  var objectName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Tensorboard_TrackableObjectGraph: @unchecked Sendable {}
extension Tensorboard_TrackableObjectGraph.TrackableObject: @unchecked Sendable {}
extension Tensorboard_TrackableObjectGraph.TrackableObject.ObjectReference: @unchecked Sendable {}
extension Tensorboard_TrackableObjectGraph.TrackableObject.SerializedTensor: @unchecked Sendable {}
extension Tensorboard_TrackableObjectGraph.TrackableObject.SlotVariableReference: @unchecked Sendable {}
extension Tensorboard_RegisteredSaver: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorboard"

extension Tensorboard_TrackableObjectGraph: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TrackableObjectGraph"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "nodes"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.nodes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nodes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.nodes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_TrackableObjectGraph, rhs: Tensorboard_TrackableObjectGraph) -> Bool {
    if lhs.nodes != rhs.nodes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_TrackableObjectGraph.TrackableObject: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_TrackableObjectGraph.protoMessageName + ".TrackableObject"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "children"),
    2: .same(proto: "attributes"),
    3: .standard(proto: "slot_variables"),
    4: .standard(proto: "registered_saver"),
    5: .standard(proto: "has_checkpoint_values"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.children) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.attributes) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.slotVariables) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._registeredSaver) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._hasCheckpointValues_p) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.children.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.children, fieldNumber: 1)
    }
    if !self.attributes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attributes, fieldNumber: 2)
    }
    if !self.slotVariables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.slotVariables, fieldNumber: 3)
    }
    try { if let v = self._registeredSaver {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._hasCheckpointValues_p {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_TrackableObjectGraph.TrackableObject, rhs: Tensorboard_TrackableObjectGraph.TrackableObject) -> Bool {
    if lhs.children != rhs.children {return false}
    if lhs.attributes != rhs.attributes {return false}
    if lhs.slotVariables != rhs.slotVariables {return false}
    if lhs._registeredSaver != rhs._registeredSaver {return false}
    if lhs._hasCheckpointValues_p != rhs._hasCheckpointValues_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_TrackableObjectGraph.TrackableObject.ObjectReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_TrackableObjectGraph.TrackableObject.protoMessageName + ".ObjectReference"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "node_id"),
    2: .standard(proto: "local_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.nodeID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.localName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.nodeID != 0 {
      try visitor.visitSingularInt32Field(value: self.nodeID, fieldNumber: 1)
    }
    if !self.localName.isEmpty {
      try visitor.visitSingularStringField(value: self.localName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_TrackableObjectGraph.TrackableObject.ObjectReference, rhs: Tensorboard_TrackableObjectGraph.TrackableObject.ObjectReference) -> Bool {
    if lhs.nodeID != rhs.nodeID {return false}
    if lhs.localName != rhs.localName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_TrackableObjectGraph.TrackableObject.SerializedTensor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_TrackableObjectGraph.TrackableObject.protoMessageName + ".SerializedTensor"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "full_name"),
    3: .standard(proto: "checkpoint_key"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fullName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.checkpointKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.fullName.isEmpty {
      try visitor.visitSingularStringField(value: self.fullName, fieldNumber: 2)
    }
    if !self.checkpointKey.isEmpty {
      try visitor.visitSingularStringField(value: self.checkpointKey, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_TrackableObjectGraph.TrackableObject.SerializedTensor, rhs: Tensorboard_TrackableObjectGraph.TrackableObject.SerializedTensor) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.fullName != rhs.fullName {return false}
    if lhs.checkpointKey != rhs.checkpointKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_TrackableObjectGraph.TrackableObject.SlotVariableReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Tensorboard_TrackableObjectGraph.TrackableObject.protoMessageName + ".SlotVariableReference"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "original_variable_node_id"),
    2: .standard(proto: "slot_name"),
    3: .standard(proto: "slot_variable_node_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.originalVariableNodeID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.slotName) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.slotVariableNodeID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.originalVariableNodeID != 0 {
      try visitor.visitSingularInt32Field(value: self.originalVariableNodeID, fieldNumber: 1)
    }
    if !self.slotName.isEmpty {
      try visitor.visitSingularStringField(value: self.slotName, fieldNumber: 2)
    }
    if self.slotVariableNodeID != 0 {
      try visitor.visitSingularInt32Field(value: self.slotVariableNodeID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_TrackableObjectGraph.TrackableObject.SlotVariableReference, rhs: Tensorboard_TrackableObjectGraph.TrackableObject.SlotVariableReference) -> Bool {
    if lhs.originalVariableNodeID != rhs.originalVariableNodeID {return false}
    if lhs.slotName != rhs.slotName {return false}
    if lhs.slotVariableNodeID != rhs.slotVariableNodeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorboard_RegisteredSaver: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisteredSaver"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "object_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.objectName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.objectName.isEmpty {
      try visitor.visitSingularStringField(value: self.objectName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tensorboard_RegisteredSaver, rhs: Tensorboard_RegisteredSaver) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.objectName != rhs.objectName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
